import type { Recipe } from '../types';

export const SEED_RECIPE: Recipe = {
  id: 'seed-tarteletter-kylling-asparges',
  title: 'Tarteletter med kylling og asparges',
  summary: 'En klassisk dansk livret med mørt kyllingebryst og hvide asparges i en cremet, opbagt sauce serveret i sprøde tarteletskaller.',
  recipeType: 'Hovedret',
  categories: ['Dansk', 'Klassisk', 'Komfort'],
  servings: 4,
  servingsUnit: 'personer',
  isSaved: false,
  ingredients: [
    { id: 'ing-1', name: 'Kyllingebryst i tern', amount: 270, unit: 'g', group: 'Kød og bouillon' },
    { id: 'ing-2', name: 'Grøntsagsbouillon', amount: 3, unit: 'dl', group: 'Kød og bouillon' },
    { id: 'ing-3', name: 'Gulerod i tern', amount: 1, unit: 'stk', group: 'Kød og bouillon' },
    { id: 'ing-4', name: 'Løg i tern', amount: 1, unit: 'stk', group: 'Kød og bouillon' },
    { id: 'ing-5', name: 'Laurbærblade', amount: 2, unit: 'stk', group: 'Kød og bouillon' },
    { id: 'ing-6', name: 'Hele peberkorn', amount: 5, unit: 'stk', group: 'Kød og bouillon' },
    { id: 'ing-7', name: 'Salt til kogning', amount: 1, unit: 'tsk', group: 'Kød og bouillon' },
    { id: 'ing-8', name: 'Smør', amount: 38, unit: 'g', group: 'Sovs' },
    { id: 'ing-9', name: 'Hvedemel', amount: 2, unit: 'spsk', group: 'Sovs' },
    { id: 'ing-10', name: 'Mælk', amount: 4, unit: 'dl', group: 'Sovs' },
    { id: 'ing-11', name: 'Hvide asparges i mindre stykker', amount: 270, unit: 'g', group: 'Fyld og smag' },
    { id: 'ing-12', name: 'Salt', amount: 0.25, unit: 'knsp', group: 'Fyld og smag' },
    { id: 'ing-13', name: 'Sort peber', amount: 0.25, unit: 'knsp', group: 'Fyld og smag' },
    { id: 'ing-14', name: 'Reven muskatnød', amount: 0.1, unit: 'knsp', group: 'Fyld og smag' },
    { id: 'ing-15', name: 'Tarteletskaller', amount: 10, unit: 'stk', group: 'Tilbehør' },
    { id: 'ing-16', name: 'Frisk persille til pynt', amount: 1, unit: 'håndfuld', group: 'Tilbehør' },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'Kom kyllingeterninger i en gryde og dæk dem med bouillon. Tilsæt gulerod, løg, laurbærblade, peberkorn og salt. Bring gryden i kog.',
      heatLevel: 9,
      heat: '9/9 – bring i kog',
      heatSource: 'ai',
      relevantIngredients: [
        { name: 'Kyllingebryst i tern', amount: 270, unit: 'g' },
        { name: 'Grøntsagsbouillon', amount: 3, unit: 'dl' },
        { name: 'Gulerod i tern', amount: 1, unit: 'stk' },
        { name: 'Løg i tern', amount: 1, unit: 'stk' },
        { name: 'Laurbærblade', amount: 2, unit: 'stk' },
        { name: 'Hele peberkorn', amount: 5, unit: 'stk' },
        { name: 'Salt til kogning', amount: 1, unit: 'tsk' },
      ],
    },
    {
      id: 'step-2',
      text: 'Skru ned for varmen, og lad kyllingen simre under låg, indtil den er gennemstegt og mør. Tag herefter kyllingen op og lad den køle kort af.',
      heatLevel: 3,
      heat: '3/9 – lav varme',
      heatSource: 'ai',
      timer: { duration: 15, description: 'Kylling simrer' },
    },
    {
      id: 'step-3',
      text: 'Tænd ovnen på 180°C varmluft. Vi skal bruge den til at varme tarteletskallerne lige om lidt.',
      heat: '180°C varmluft',
      reminder: 'Forvarm ovnen til 180 grader',
    },
    {
      id: 'step-4',
      text: 'Smelt smørret i en ren gryde. Tilsæt hvedemel og rør godt rundt, til du har en jævn melbolle. Lad det stege i et minuts tid under omrøring, så melsmagen forsvinder.',
      heatLevel: 5,
      heat: '5/9 – middel varme',
      heatSource: 'ai',
      timer: { duration: 1, description: 'Melbolle steges' },
      relevantIngredients: [
        { name: 'Smør', amount: 38, unit: 'g' },
        { name: 'Hvedemel', amount: 2, unit: 'spsk' },
      ],
    },
    {
      id: 'step-5',
      text: 'Tilsæt mælken gradvist, mens du pisker grundigt, så der ikke kommer klumper. Lad saucen koge op under konstant omrøring, indtil den tykner.',
      heatLevel: 6,
      heat: '6/9 – rolig stegning',
      heatSource: 'ai',
      relevantIngredients: [
        { name: 'Mælk', amount: 4, unit: 'dl' },
      ],
    },
    {
      id: 'step-6',
      text: 'Sæt tarteletskallerne i ovnen. Vend dem gerne med bunden opad, så de bliver ekstra sprøde.',
      relevantIngredients: [
        { name: 'Tarteletskaller', amount: 10, unit: 'stk' },
      ],
      timer: { duration: 5, description: 'Tarteletskaller varmes' },
    },
    {
      id: 'step-7',
      text: 'Vend de kogte kyllingeterninger og de drænede hvide asparges i saucen. Lad det simre forsigtigt, indtil det er helt varmet igennem. Smag til med salt, peber og eventuelt muskatnød.',
      heatLevel: 4,
      heat: '4/9 – middel-lav varme',
      heatSource: 'ai',
      relevantIngredients: [
        { name: 'Hvide asparges i mindre stykker', amount: 270, unit: 'g' },
        { name: 'Salt', amount: 0.25, unit: 'knsp' },
        { name: 'Sort peber', amount: 0.25, unit: 'knsp' },
        { name: 'Reven muskatnød', amount: 0.1, unit: 'knsp' },
      ],
    },
    {
      id: 'step-8',
      text: 'Fordel det varme fyld i de sprøde tarteletskaller. Pynt med frisk persille og server straks.',
      relevantIngredients: [
        { name: 'Frisk persille til pynt', amount: 1, unit: 'håndfuld' },
      ],
    },
  ],
  tipsAndTricks: [
    'Si bouillonen efter kogning og brug den som base til saucen for ekstra smag.',
    'Pisk mælken i gradvist for at undgå klumper i béchamelen.',
    'Tarteletskallerne kan vendes med bunden opad i ovnen for ekstra sprødhed.',
  ],
  lastUsed: new Date().toISOString(),
};
