export const STORAGE_KEYS = {
  recipes: 'cookmoxs_recipes_v1',
  folders: 'cookmoxs_folders_v1',
  activeRecipe: 'cookmoxs_active_v1',
  theme: 'cookmoxs_theme',
  darkMode: 'cookmoxs_dark_mode',
  userLevel: 'cookmoxs_user_level',
  importPreference: 'cookmoxs_import_preference',
  lastBackupAt: 'cookmoxs_last_backup_at',
  lastCloudSyncAt: 'cookmoxs_last_cloud_sync_at',
  cookFontSize: 'cookmoxs_cook_font_size',
  nutritionToolsEnabled: 'cookmoxs_nutrition_tools_enabled',
  learningProfile: 'cookmoxs_learning_profile_v1',
  learningFeedbackEnabled: 'cookmoxs_learning_feedback_enabled',
} as const;
