// Generated by scripts/sync-cache-version.mjs. Do not edit manually.
export const APP_BUILD_VERSION = '1.1.1';
export const APP_SHELL_CACHE_NAME = 'cookmoxs-v1-1-1';
export const RECIPE_CACHE_NAME = 'cookmoxs-recipes-v1-1-1';
